name = "MyJuliaRegistry"
uuid = "4cb3ea66-6044-4c59-8581-44fb59a0b20a"
repo = "https://github.com/benninkrs/MyJuliaRegistry.jl"
description = "Ryan S. Bennink's personal Julia registry"

[packages]
2532fb96-5642-438b-b515-97252d17ad77 = { name = "SuperTuples", path = "S/SuperTuples" }
284fb2d5-051f-46d8-adb4-4fe3216759af = { name = "InheritableFields", path = "I/InheritableFields" }
2e5e676e-f03b-4176-b8e1-22a77afa639b = { name = "TypeTools", path = "T/TypeTools" }
35096534-6a70-4072-b012-2b6df64b3c53 = { name = "MiscUtils", path = "M/MiscUtils" }
4f6a5be9-6cd1-4bca-9e4c-190b27da7509 = { name = "AlgebraicTensors", path = "A/AlgebraicTensors" }
